---
apiVersion: v1
kind: Service
metadata:
  name: common-datax-web-executor
spec:
  ports:
    - name: api
#      nodePort: 50808
      port: 8080
      protocol: TCP
      targetPort: executor
  selector:
    app: common-datax-web-executor
#  type: NodePort
