---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datax-web-mysql-pv-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
